# kNN algorithm using python

## Import the libraries & dataset Iris from the Kaggle 


In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
#Using open source dataset from Kaggle 
ds = pd.read_csv("/Users/ismail/Documents/Study/LfD/archive/Iris.csv")
#from sklearn.datasets import load_iris
#iris = load_iris()

<h4>Read the first entries</h4>

In [2]:
ds.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

<h5>
    The iloc indexer for Pandas Dataframe is used for integer-location based indexing / selection by position. “iloc” in pandas is used to select rows and columns by number, in the order that they appear in the data frame. </h5>


In [3]:
x = ds.iloc[:,1:5]
x.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [4]:
y = ds.iloc[:,-1]
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [5]:
ds.shape

(150, 6)

In [6]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [7]:
np.sqrt(150)

12.24744871391589

In [8]:
knn = KNeighborsClassifier(n_neighbors = 12)

In [9]:
knn.fit(x,y)

KNeighborsClassifier(n_neighbors=12)

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = .3)

In [12]:
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=12)

### make predictions

In [13]:
y_test_pred = knn.predict(x_test)
y_test_pred

array(['Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica'], dtype=object)

In [14]:
prediction_output = pd.DataFrame(data = [y_test_pred, y_test])
prediction_output.transpose()

0                1
0   Iris-versicolor  Iris-versicolor
1   Iris-versicolor  Iris-versicolor
2   Iris-versicolor  Iris-versicolor
3   Iris-versicolor  Iris-versicolor
4    Iris-virginica   Iris-virginica
5   Iris-versicolor  Iris-versicolor
6    Iris-virginica   Iris-virginica
7    Iris-virginica   Iris-virginica
8    Iris-virginica   Iris-virginica
9       Iris-setosa      Iris-setosa
10   Iris-virginica   Iris-virginica
11   Iris-virginica   Iris-virginica
12  Iris-versicolor  Iris-versicolor
13      Iris-setosa      Iris-setosa
14      Iris-setosa      Iris-setosa
15   Iris-virginica   Iris-virginica
16      Iris-setosa      Iris-setosa
17  Iris-versicolor   Iris-virginica
18      Iris-setosa      Iris-setosa
19  Iris-versicolor  Iris-versicolor
20  Iris-versicolor   Iris-virginica
21      Iris-setosa      Iris-setosa
22      Iris-setosa      Iris-setosa
23      Iris-setosa      Iris-setosa
24   Iris-virginica   Iris-virginica
25   Iris-virginica   Iris-virginica
26   Iris-virginica   Iris-virginica
27  Iris-versicolor  Iris-versicolor
28   Iris-virginica   Iris-virginica
29   Iris-virginica   Iris-virginica
30   Iris-virginica   Iris-virginica
31   Iris-virginica   Iris-virginica
32      Iris-setosa      Iris-setosa
33      Iris-setosa      Iris-setosa
34   Iris-virginica   Iris-virginica
35      Iris-setosa      Iris-setosa
36  Iris-versicolor  Iris-versicolor
37  Iris-versicolor  Iris-versicolor
38  Iris-versicolor  Iris-versicolor
39      Iris-setosa      Iris-setosa
40   Iris-virginica   Iris-virginica
41      Iris-setosa      Iris-setosa
42   Iris-virginica   Iris-virginica
43      Iris-setosa      Iris-setosa
44   Iris-virginica   Iris-virginica

### Evaluating the Algorithm

In [15]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_test_pred))
#print(classification_report(y_test, y_test_pred))

[[14  0  0]
 [ 0 11  0]
 [ 0  2 18]]


In [16]:
print("Accuracy:", knn.score(x_test,y_test))

Accuracy: 0.9555555555555556


In [ ]:
for i in range (1,15):
    knn2=KNeighborsClassifier(n_neighbors=i)
    knn2.fit(x_train, y_train)
    print("For k = %d accuracy is"%i,knn2.score(x_test,y_test))

For k = 1 accuracy is 0.9333333333333333
For k = 2 accuracy is 0.9111111111111111
For k = 3 accuracy is 0.9555555555555556
For k = 4 accuracy is 0.9555555555555556
For k = 5 accuracy is 0.9777777777777777
For k = 6 accuracy is 0.9555555555555556
For k = 7 accuracy is 0.9777777777777777
For k = 8 accuracy is 0.9333333333333333
For k = 9 accuracy is 0.9555555555555556
For k = 10 accuracy is 0.9333333333333333
For k = 11 accuracy is 0.9777777777777777
For k = 12 accuracy is 0.9555555555555556
For k = 13 accuracy is 0.9333333333333333
For k = 14 accuracy is 0.9555555555555556
